### PR TITLE
Update Saved Searches chapter

### PR DESCRIPTION
**Pull request by mizuOda**
Updated Saved Searches chapter as follows:
- add Control Codes info to saved_searches.xhtml as text and delete reference to saved-searches-control-codes.png — saves 245K
- delete saved-searches-control-codes.png (because info has been added to xhtml file as text)
- add updated saved-searches-context-menu.png that shows "Fill Controls" command in 1.6.0+
- add updated .opf that reflects deletion of saved-searches-control-codes.png and addition of updated saved-searches-context-menu.png

### CODE REVIEW

**Comment by kevinhendricks** [comment]
There is one typo in line 98 of saved searches text:

Tabbled -> Tabbed.

Please fix that by making the change on your end and committing it and I will merge the resulting PR.

Thank You!

**Comment by dougmassay** [comment]
Just push another commit with the change to your fork. It will automatically be added to this Pull Request. Didn't want you to be worried about having to jump through any special hoops to make this happen. Same for your other Pull Request.

**Comment by mizuOda** [comment]
Sorry about the typo! Thanks for explaining how to fix it with another commit. I was a little befuddled trying to figure out how to do that without starting over. This whole process has been a great learning experience.

**Comment by dougmassay** [comment]
I figured you might be sweating it a bit. ;)  know I was a bit nervous at first when someone asked me to update my pull request. As long as you haven't made other changes to your fork in the meantime, you can push as many commits as you want and they'll be added to your pull request.

Thanks for the changes!

**Comment by kevinhendricks** [comment]
Yes, looks good!  Thank you.

**Comment by mizuOda** [comment]
Awesome! I am very excited to be learning how to do pull requests. I can't contribute to code, but I am thrilled to be able to contribute to documentation! 😄

**Pull request merged**
